# Generated by Django 5.0.6 on 2026-03-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_permissions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
