# Generated by Django 5.0.6 on 2026-03-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='mois_payes',
            field=models.IntegerField(default=0),
        ),
    ]
