# Generated by Django 5.0.6 on 2026-03-13 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_absence_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CahierTexte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('contenu_cours', models.TextField(blank=True)),
                ('devoirs', models.TextField(blank=True)),
                ('date_remise_devoirs', models.DateField(blank=True, null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cahier_texte', to='school.classe')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cahier_texte', to='school.enseignant')),
            ],
            options={
                'verbose_name': 'Cahier de texte',
                'verbose_name_plural': 'Cahiers de texte',
                'ordering': ['-date'],
            },
        ),
    ]
